apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: ${{values.component_id}}
spec:
  name: ${{values.component_id}}
  use_keyless: true
  protocol: http
  active: true
  proxy:
    target_url: ${{values.target_url}}
    listen_path: /${{values.component_id}}/
    strip_listen_path: true    
